# Generated by Django 2.1 on 2019-10-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0002_auto_20191023_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='circle',
            name='is_limited',
            field=models.BooleanField(default=False, help_text='Limited circles can grow up to a fixed number of members.', verbose_name='limited'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Public circles are listed in the main page so everyone know about their existence.'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='circles/pictures'),
        ),
        migrations.AlterField(
            model_name='circle',
            name='verified',
            field=models.BooleanField(default=False, help_text='Verified circles are also known as official communities.', verbose_name='verified circle'),
        ),
    ]
